//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FizzBuzzClient.WCFFizzBuzzServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFFizzBuzzServiceReference.IWCFFizzBuzzService")]
    public interface IWCFFizzBuzzService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFFizzBuzzService/GetData", ReplyAction="http://tempuri.org/IWCFFizzBuzzService/GetDataResponse")]
        string[] GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFFizzBuzzService/GetData", ReplyAction="http://tempuri.org/IWCFFizzBuzzService/GetDataResponse")]
        System.Threading.Tasks.Task<string[]> GetDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFFizzBuzzServiceChannel : FizzBuzzClient.WCFFizzBuzzServiceReference.IWCFFizzBuzzService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFFizzBuzzServiceClient : System.ServiceModel.ClientBase<FizzBuzzClient.WCFFizzBuzzServiceReference.IWCFFizzBuzzService>, FizzBuzzClient.WCFFizzBuzzServiceReference.IWCFFizzBuzzService {
        
        public WCFFizzBuzzServiceClient() {
        }
        
        public WCFFizzBuzzServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFFizzBuzzServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFFizzBuzzServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFFizzBuzzServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string[]> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
    }
}
